#!/usr/bin/env bash
# ============================================================================
# 04_run_mmpbsa_8.sh — gmx_MMPBSA on the 8 candidates.
#
# For each compound i in 1..8:
#   - reads config.yaml for the frame window (default 70-100 ns)
#   - builds mmpbsa.in (PB + GB, 0.15 M salt)
#   - runs gmx_MMPBSA using group names Protein and LIG from index.ndx
#   - parses FINAL_RESULTS_MMPBSA.dat → mmpbsa_summary.json
#
# Idempotent: skips compounds where mmpbsa_summary.json already exists.
# Continues past PB failures because GB is often still valid.
# ============================================================================
set -eo pipefail   # NOTE: no -u; conda activate hooks reference unset vars
IFS=$'\n\t'

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
CFG="${SCRIPT_DIR}/config.yaml"

# ── Parse config ────────────────────────────────────────────────────────
eval "$(python3 - "$CFG" <<'PYEOF'
import sys, yaml
c = yaml.safe_load(open(sys.argv[1]))
kv = {
    "output_dir":       c["output_dir"],
    "mmpbsa_executable":c.get("mmpbsa_executable", "gmx_MMPBSA"),
    "mmpbsa_start_ns":  c["mmpbsa_start_ns"],
    "mmpbsa_end_ns":    c["mmpbsa_end_ns"],
    "mmpbsa_n_frames":  c["mmpbsa_n_frames"],
    "mmpbsa_interval_frames": c["mmpbsa_interval_frames"],
    "ion_conc_M":       c["ion_conc_M"],
    "final_n_candidates": c["final_n_candidates"],
    "md_output_dt_ps":  c["md_output_dt_ps"],
    "temperature_K":    c["temperature_K"],
}
for k, v in kv.items():
    print(f'{k}="{v}"')
PYEOF
)"

md_root="${output_dir}/md"
log_dir="${output_dir}/logs"
mkdir -p "${log_dir}"

# Compute frame indices (integer) from ns × 1000 / md_output_dt_ps
start_frame=$(python3 -c "print(int(${mmpbsa_start_ns} * 1000 / ${md_output_dt_ps}))")
end_frame=$(python3   -c "print(int(${mmpbsa_end_ns}   * 1000 / ${md_output_dt_ps}))")

echo "============================================================"
echo "  04_run_mmpbsa_8 — MMPBSA on frames [${start_frame}, ${end_frame}]"
echo "  interval ${mmpbsa_interval_frames} → ~${mmpbsa_n_frames} frames"
echo "============================================================"

run_one () {
    local i="$1"
    local wd="${md_root}/comp_${i}"
    local log="${log_dir}/mmpbsa_comp_${i}.log"

    if [[ ! -f "${wd}/md.tpr" ]]; then
        echo "comp_${i}: no md.tpr — MD not finished, skipping"
        return 1
    fi
    if [[ -f "${wd}/mmpbsa_summary.json" ]]; then
        echo "comp_${i}: mmpbsa_summary.json exists → skip"
        return 0
    fi

    (
        cd "${wd}"
        exec > >(tee -a "${log}") 2>&1
        echo "──────── mmpbsa comp_${i} @ $(date '+%F %T') ────────"

        # 1. Emit mmpbsa.in
        cat > mmpbsa.in <<EOF
Input file for MMPBSA — generated by 04_run_mmpbsa_8.sh
&general
  startframe = ${start_frame}
  endframe   = ${end_frame}
  interval   = ${mmpbsa_interval_frames}
  verbose    = 1
  temperature = ${temperature_K}
  keep_files = 0
  PBRadii     = 4              ; mbondi3 (matches implicit-solvent GB=8; robust for GAFF2)
/
&pb
  istrng    = ${ion_conc_M}
  fillratio = 4.0
  radiopt   = 0               ; use radii from topology (set above by PBRadii)
  inp       = 2               ; SASA-based non-polar term
/
&gb
  igb       = 8               ; GB-Neck2 (more accurate than igb=5, still fast)
  saltcon   = ${ion_conc_M}
/
EOF

        # 2. Run gmx_MMPBSA — use group names to avoid brittle numeric IDs.
        # gmx_MMPBSA 1.6.4 doesn't recognise GROMACS 2025. If a 2018-2024
        # gmx is available (typically in the `nlrp3` env after installing
        # 'gromacs<2025', or in a dedicated 'mmpbsa' env), prefer that one;
        # otherwise fall back to gmx_cuda's 2025 and let gmx_MMPBSA fail
        # gracefully (Table 5.9 will show 'gmx_incompatibility' for those
        # compounds and downstream stages continue).
        prefer_gmx=""
        for cand in \
            "${HOME}/miniconda3/envs/mmpbsa/bin/gmx" \
            "${HOME}/miniconda3/envs/nlrp3/bin/gmx"; do
            if [[ -x "${cand}" ]]; then
                ver=$("${cand}" --version 2>/dev/null | awk '/^GROMACS/{print $NF; exit}')
                case "${ver}" in
                    2018.*|2019.*|2020.*|2021.*|2022.*|2023.*|2024.*)
                        prefer_gmx="$(dirname "${cand}")"
                        echo "  [env] prepending ${prefer_gmx} to PATH (gmx ${ver} — MMPBSA-compatible)"
                        break;;
                esac
            fi
        done
        if [[ -z "${prefer_gmx}" ]]; then
            # No compatible gmx found — fall back to gmx_cuda; MMPBSA may fail
            gmx_cuda_bin="${HOME}/miniconda3/envs/gmx_cuda/bin"
            if [[ -x "${gmx_cuda_bin}/gmx" ]]; then
                echo "  [env] no MMPBSA-compatible gmx (2018-2024) found; using gmx_cuda's gmx 2025 (MMPBSA likely to fail — install 'gromacs<2025' in nlrp3 env to fix)"
                export PATH="${gmx_cuda_bin}:${PATH}"
            fi
        else
            export PATH="${prefer_gmx}:${PATH}"
        fi
        set +e
        ${mmpbsa_executable} -O -i mmpbsa.in \
            -cs md.tpr -ci index.ndx -cg Protein LIG \
            -ct md.xtc -cp topol.top \
            -o FINAL_RESULTS_MMPBSA.dat \
            -eo FINAL_RESULTS_MMPBSA.csv
        rc=$?
        set -e
        if [[ $rc -ne 0 ]]; then
            echo "comp_${i}: gmx_MMPBSA returned ${rc} — will attempt to parse anyway"
        fi

        # 3. Parse to JSON
        python3 - "${i}" <<'PYEOF'
import json, re, sys
from pathlib import Path

idx = int(sys.argv[1])
dat = Path('FINAL_RESULTS_MMPBSA.dat')
summary = {'compound_idx': idx}
if not dat.exists():
    Path('mmpbsa_summary.json').write_text(json.dumps(
        {**summary, 'status': 'no_dat_file'}, indent=2))
    print(f'comp_{idx}: no FINAL_RESULTS_MMPBSA.dat')
    sys.exit(0)

text = dat.read_text()

# gmx_MMPBSA blocks are labelled "GENERALIZED BORN" / "POISSON BOLTZMANN"
def extract_block(name):
    m = re.search(rf'{name}.*?DELTA TOTAL\s+([\-0-9\.eE+]+)\s+([\-0-9\.eE+]+)\s+([\-0-9\.eE+]+)',
                  text, re.DOTALL | re.IGNORECASE)
    if not m: return None
    return dict(deltaG=float(m.group(1)), std=float(m.group(2)), sem=float(m.group(3)))

def extract_component(block_name, comp_name):
    # Find within a specific block, the row starting with the component name.
    b = re.search(rf'{block_name}.*?(?:GENERALIZED|POISSON|\Z)', text, re.DOTALL | re.IGNORECASE)
    if not b: return None
    seg = b.group(0)
    m = re.search(rf'^\s*{comp_name}\s+([\-0-9\.eE+]+)\s+([\-0-9\.eE+]+)\s+([\-0-9\.eE+]+)',
                  seg, re.MULTILINE)
    if not m: return None
    return dict(value=float(m.group(1)), std=float(m.group(2)), sem=float(m.group(3)))

summary['gb'] = extract_block('GENERALIZED BORN')
summary['pb'] = extract_block('POISSON BOLTZMANN')

for comp in ('VDWAALS', 'EEL', 'EGB', 'ESURF', 'EPB', 'ENPOLAR', 'EDISPER'):
    for block, key in (('GENERALIZED BORN', 'gb'), ('POISSON BOLTZMANN', 'pb')):
        v = extract_component(block, comp)
        if v is not None:
            summary.setdefault(f'{key}_components', {})[comp] = v
summary['status'] = 'ok' if (summary.get('pb') or summary.get('gb')) else 'parse_fail'
Path('mmpbsa_summary.json').write_text(json.dumps(summary, indent=2))
print(f'comp_{idx}: PB ΔG={summary.get("pb")}  GB ΔG={summary.get("gb")}')
PYEOF
    ) || {
        echo "comp_${i}: MMPBSA FAILED — see ${log}"
        return 1
    }
}

for i in $(seq 1 "${final_n_candidates}"); do
    echo ""
    echo "══════════ MMPBSA compound ${i}/${final_n_candidates} ══════════"
    run_one "${i}" || echo "→ comp_${i} MMPBSA failed, continuing"
done

echo ""
echo "[$(date '+%F %T')] 04_run_mmpbsa_8 finished."
echo "Next: python3 ${SCRIPT_DIR}/05_run_admet_full.py"
